server:
  port: ${vcap.application.port}

eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka/


---
spring:
  profiles: peer
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri}/eureka/
